# Generated by Django 6.1.1 on 2026-10-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vet_clinic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veterinarian",
            name="specialization",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="veterinarian",
            name="years_of_experience",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
