# Generated by Django 6.1.1 on 2026-10-04 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vet_clinic", "0002_alter_veterinarian_specialization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="animal_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pets",
                to="vet_clinic.animaltype",
            ),
        ),
        migrations.AlterField(
            model_name="veterinarian",
            name="specialization",
            field=models.CharField(
                blank=True, default="General practice", max_length=255
            ),
        ),
    ]
