# Generated by Django 6.1.1 on 2026-10-05 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vet_clinic", "0003_alter_pet_animal_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="veterinarians",
            field=models.ManyToManyField(
                blank=True, related_name="pets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
