# Generated by Django 6.1.1 on 2026-10-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_clinic', '0004_alter_pet_veterinarians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarian',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
